name: Profile Stats

on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-contribution-grid-snake.svg
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Add changes
        run: git add -A

      - name: Generate Stats
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
